name: 编译内核-紫罗兰

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4



    - name: 构建编译内核环境
      run: |
        sudo apt-get update
        sudo -E apt-get -y -qq install git make bc bison ccache openssl dos2unix zip kmod cpio flex libelf-dev curl libssl-dev libtfm-dev wget device-tree-compiler ca-certificates python3 binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace



    - name: 下载 Gcc编译器
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        
        mkdir gcc64
        wget -O gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
        tar -C gcc64/ -zxvf gcc-aarch64.tar.gz
    
        mkdir gcc32
        wget -O gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
        tar -C gcc32/ -zxvf gcc-arm.tar.gz
    
    - name: 下载Clang编译器
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        mkdir clang-aosp
        git clone https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-6443078 clang-aosp
    
    
    - name: 下载内核源码
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/srxhip/kernel-4.14.git
        cd kernel-4.14
               
    - name: 设置ccache缓存
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: build-kernel-mido-kernel
        max-size: 2G

    - name: 开启LXC/Docker内核配置
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        wget https://github.com/wu17481748/lxc-docker/releases/download/lxc-docker-2config/LXC-DOCKER-OPEN-CONFIG.sh
        chmod +x LXC-DOCKER-OPEN-CONFIG.sh
        ./LXC-DOCKER-OPEN-CONFIG.sh kernel-4.14/arch/arm64/configs/a_defconfig -w

    - name: 禁用 task_turbo 模块
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/kernel-4.14
        sed -i '/CONFIG_MTK_TASK_TURBO/d' arch/arm64/configs/a_defconfig
        echo "# CONFIG_MTK_TASK_TURBO is not set" >> arch/arm64/configs/a_defconfig


    - name: 打入LXC补丁(runc)
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        wget https://raw.githubusercontent.com/tomxi1997/lxc-docker-support-for-android/refs/heads/main/runcpatch.sh
        chmod +x runcpatch.sh
        if [ -f kernel-4.14/kernel/cgroup.c ]; then
          ./runcpatch.sh kernel-4.14/kernel/cgroup.c
        fi
        if [ -f kernel-4.14/kernel/cgroup/cgroup.c ]; then
          ./runcpatch.sh kernel-4.14/kernel/cgroup/cgroup.c
        fi

    - name: 打入xt_qtaguid补丁
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        if [ -f kernel-4.14/net/netfilter/xt_qtaguid.c ]; then
          wget https://github.com/wu17481748/lxc-docker/releases/download/lxc/lxc.patch
          patch -p0 < lxc.patch
        fi

    - name: 关闭ANDROID_PARANOID_NETWORK
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        sed -i '/CONFIG_ANDROID_PARANOID_NETWORK/d' kernel-4.14/arch/arm64/configs/a_defconfig
        echo "# CONFIG_ANDROID_PARANOID_NETWORK is not set" >> kernel-4.14/arch/arm64/configs/a_defconfig

    - name: 开启KVM配置
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        echo "CONFIG_VIRTUALIZATION=y" >> kernel-4.14/arch/arm64/configs/a_defconfig
        echo "CONFIG_KVM=y" >> kernel-4.14/arch/arm64/configs/a_defconfig
        echo "CONFIG_VHOST_NET=y" >> kernel-4.14/arch/arm64/configs/a_defconfig
        echo "CONFIG_VHOST_CROSS_ENDIAN_LEGACY=y" >> kernel-4.14/arch/arm64/configs/a_defconfig

    - name: kernelsu legacy patch
      run: |
        echo "KSU_LOG: 开始下载并应用 RKSU 官方 4.14 patch"
        
        cd $GITHUB_WORKSPACE/kernel_workspace/kernel-4.14

        
        wget https://github.com/rksuorg/kernel_patches/raw/master/manual_hook/kernel-4.14.patch -O ksu-4.14.patch || { echo "下载 patch 失败"; exit 1; }

        
        patch -p1 < ksu-4.14.patch || { echo "patch 应用失败"; cat ksu-4.14.patch; exit 1; }

        
    - name: kernelsu stage
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/kernel-4.14
        rm -rf KernelSU
        curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash

    - name: 开始编译内核
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/kernel-4.14
        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$GITHUB_WORKSPACE/kernel_workspace/gcc64/bin:$GITHUB_WORKSPACE/kernel_workspace/gcc32/bin:$PATH
        export KBUILD_BUILD_HOST=EA
        export KBUILD_BUILD_USER=ZLL

          make -j$(nproc --all)   O=out \
                        ARCH=arm64 \
                        CC="clang" \
                        CLANG_TRIPLE=aarch64-linux-gnu- \
                        CROSS_COMPILE=aarch64-linux-android- \
                        CROSS_COMPILE_ARM32=arm-linux-androideabi-" \
                        LD=ld.lld \
                        AS=llvm-as \
                        AR=llvm-ar \
                        NM=llvm-nm \
                        LLVM_IAS=1 \
                        OBJCOPY=llvm-objcopy \
                        a_defconfig
          make -j$(nproc --all)  CC="ccache clang"  O=out \
                        ARCH=arm64 \
                        CC="clang" \
                        CLANG_TRIPLE=aarch64-linux-gnu- \
                        CROSS_COMPILE=aarch64-linux-android- \
                        CROSS_COMPILE_ARM32=arm-linux-androideabi-" \
                        LD=ld.lld \
                        AS=llvm-as \
                        AR=llvm-ar \
                        NM=llvm-nm \
                        LLVM_IAS=1 \
                        OBJCOPY=llvm-objcopy \
                        CONFIG_NO_ERROR_ON_MISMATCH=y
      
                

    - name: 制作Anykernel3卡刷包
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/osm0sis/AnyKernel3
        sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
        sed -i 's!block=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!block=auto;!g' AnyKernel3/anykernel.sh
        sed -i 's/is_slot_device=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
        cp kernel-4.14/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        rm -rf AnyKernel3/.git* AnyKernel3/README.md
        
    
    
    - name: 上传 Anykernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel.zip
        path: kernel_workspace/AnyKernel3/*
    
    
    - name: 上传内核配置 .config
      uses: actions/upload-artifact@v4
      with:
        name: kernel-config
        path: kernel_workspace/kernel-4.14/out/.config
        include-hidden-files: true


    - name: 上传编译内核
      uses: actions/upload-artifact@v4
      with:
        name: kernel-Image
        path: kernel_workspace/kernel-4.14/out/arch/arm64/boot/Image
